### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by 0marAmara** [ahmeddelattarr/SyntaxSphere#34]
Implementation of the profile page
- [x] Using username across all the app 
- [x] Validating username in front and backend
- [x] Implementing it in the frontend

**Comment by ahmeddelattarr** [comment]
username[¶](https://docs.djangoproject.com/en/5.1/ref/contrib/auth/#django.contrib.auth.models.User.username)
Required. 150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters.

The max_length should be sufficient for many use cases. If you need a longer length, please use a [custom user model](https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#specifying-custom-user-model). If you use MySQL with the utf8mb4 encoding (recommended for proper Unicode support), specify at most max_length=191 because MySQL can only create unique indexes with 191 characters in that case by default.
